name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@1868a545ffb91bdc221d14a168b5b6d8de4a28b3 # main, to use supported NodeJS
      - name: Run tests
        uses: tree-sitter/parser-test-action@e9b2fecb014a7f8caa1a47316450d4e665132ed9 # main, to use supported NodeJS
        with:
          test-rust: false
      - name: Download examples
        # TODO: find more real-life examples, especially if they are currently buggy
        run: |
          curl https://raw.githubusercontent.com/actix/actix/master/justfile > examples/actix.just
      - name: Parse examples
        uses: tree-sitter/parse-action@041309e0e4db07278911ee87985bddb958f877e1 # main, to use supported NodeJS
        with:
          files: examples/**/*.just
