name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@cd96f2c296346c12cf539df3e5cd00102a1f2340 # v2
      - name: Run tests
        uses: tree-sitter/parser-test-action@1f7ad83f2358970a13cd62ca1859eafc3326d669 # v2
        with:
          test-rust: false
      - name: Download examples
        # TODO: find more real-life examples, especially if they are currently buggy
        run: |
          curl https://raw.githubusercontent.com/actix/actix/master/justfile > examples/actix.just
      - name: Parse examples
        uses: tree-sitter/parse-action@f44ffa94f802024f27e821a72e6f2f3efc5dd521 #v4
        with:
          files: examples/**/*.just
